### ISSUE TITLE
[fog][DEPRECATION] Unable to load Fog::OpenNebula::Compute ...

### ISSUE THREAD

**Issue by cphoward** [fog/fog-opennebula#2]
Hello @dann1 

I am getting the following deprecation warnings:
```
[fog][DEPRECATION] Unable to load Fog::OpenNebula::Compute
[fog][DEPRECATION] The format Fog::Compute::OpenNebula is deprecated
```

I am using the `Compute` constructor as shown in the README.md:

```
Fog::Compute.new(
  provider: 'OpenNebula',
  opennebula_username: 'oneadmin',
  opennebula_password: 'password',
  opennebula_endpoint: 'http://localhost:2633/RPC2'
)
```

How can I get rid of the deprecation warnings?

**Comment by cphoward** [comment]
It appears that 

```
Fog::Compute::OpenNebula.new(...)
```

eliminates the deprecation notice.

**Comment by cphoward** [comment]
I have opened another ticket with test-kitchen to understand how test kitchen loads drivers (not related to the README or project specific issues here). I am getting the same deprecation warnings on another project as well. Only adding here in case you have any insight into the problem.

https://github.com/test-kitchen/test-kitchen/issues/1607

**Comment by dann1** [comment]
Hi @cphoward, I have updated the gemspec to specify the fog-core version without deprecation warnings. I found some issues with the warnings https://github.com/fog/fog-aws/issues/466 and https://github.com/fog/fog-google/issues/417. In order to use the latest fog version it is required a somewhat long renaming task in the code.
